#!/usr/bin/env zsh
DEBUG=${DEBUG:-false}
#DEBUG=${DEBUG:-true}
if $DEBUG; then
    echo "-------------------------" >> ~/tmp/loginpaths.txt
    echo "zshrc> Start of execution" >> ~/tmp/loginpaths.txt
    echo "zshrc> PATH: ${PATH}" >> ~/tmp/loginpaths.txt
    echo "zshrc> path: ${path}" >> ~/tmp/loginpaths.txt
fi

# Location of my dotfiles
DOTFILES=$HOME/.dotfiles

# Update PATH
# typeset -U path

export PATH=$HOME/bin:$HOME/scripts:/usr/local/bin:/usr/local/sbin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/opt/local/bin:/opt/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:$DOTFILES/scripts:$PATH

export HISTSIZE=32768;
export HISTFILESIZE=$HISTSIZE;
export HISTFILE=${HOME}/.zsh_history
export CLICOLOR=1
export EDITOR='vim'
export PAGER='less'
export ZSH=${HOME}/.zgen/robbyrussell/oh-my-zsh-master
export TERM=screen-256color-bce
# export TERM=xterm-256color
export LANG=en_US.UTF-8
export LC_ALL="en_US.UTF-8"
export EDITOR='vim'
export PATH="/anaconda3/bin:$PATH"
export LESS=-FXJAIMqj.5

if $DEBUG; then
    echo "zshenv> PATH: ${PATH}" >> ~/tmp/loginpaths.txt
    echo "zshenv> path: ${path}" >> ~/tmp/loginpaths.txt
    echo "zshenv> End of execution" >> ~/tmp/loginpaths.txt
    echo "--------------------------" >> ~/tmp/loginpaths.txt
fi

if [[ -f ~/perl5/perlbrew/etc/bashrc ]]; then
    source ~/perl5/perlbrew/etc/bashrc
fi
source "$HOME/.cargo/env"
