#!/usr/bin/env zsh
export HISTSIZE=32768;
export HISTFILESIZE=$HISTSIZE;
export CLICOLOR=1
export EDITOR='vim'
export PAGER='less'
export ZSH=${HOME}/.zgen/robbyrussell/oh-my-zsh-master
export TERM=screen-256color
# export TERM=xterm-256color
export LANG=en_US.UTF-8
export LC_ALL="en_US.UTF-8"
export EDITOR='vim'
export PATH="/anaconda3/bin:$PATH"
export LESS=-FXJAIMqj.5
