# begin section 1
# This first section adapted from https://www.outcoldman.com/en/archive/2015/09/13/keep-your-sh-together/

# If I see that zsh takes to much time to load I profile what has been changed,
# I want to see my shell ready in not more than 1 second
PROFILING=${PROFILING:-false}
# PROFILING=${PROFILING:-true}
if $PROFILING; then
    zmodload zsh/zprof
fi

# Location of my dotfiles
DOTFILES=$HOME/.dotfiles
# PLUGINS=${DOTFILES}/plugins

# Update PATH
path=(
    $HOME/bin
    $HOME/scripts
    /usr/local/bin
    /usr/local/sbin
    /opt/local/bin
    /opt/local/sbin
    /bin
    /sbin
    /usr/bin
    /usr/sbin
    $DOTFILES/scripts
    $path
)
typeset -U path

# if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# change the size of history files
#export HISTSIZE=32768;
#export HISTFILESIZE=$HISTSIZE;

# Autoenv https://github.com/Tarrasch/zsh-autoenv
# Plugin to automatically modify path when it sees .env file
# AUTOENV_FILE_ENTER=.env
# AUTOENV_FILE_LEAVE=.env1

# tmux plugin settings
# this always starts tmux
ZSH_TMUX_AUTOSTART_ONCE=true
ZSH_TMUX_FIXTERM=true
ZSH_TMUX_AUTOQUIT=false # not sure what this does, may remove later

# set DEFAULT_USER based on different environments
if [[ $OSTYPE =~ 'darwin' ]]; then
    if [[ `hostname` = 'WDXJW68539TD8' ]]; then
        DEFAULT_USER=jw68539
    else
        DEFAULT_USER=jon
    fi
else
    DEFAULT_USER=pi
fi


# Remove the history (fc -l) command from the history list when invoked.
setopt histnostore
# Remove superfluous blanks from each command line being added to the history list.
setopt histreduceblanks

# end section 1

# use vi bindings
bindkey -v
source ~/.zshenv


#export HISTSIZE=32768;
#export HISTFILESIZE=$HISTSIZE;
#export CLICOLOR=1
#export EDITOR='vim'
#export PAGER='less'
#export ZSH=${HOME}/.zgen/robbyrussell/oh-my-zsh-master
#export TERM=screen-256color
# export TERM=xterm-256color
#export LANG=en_US.UTF-8
#export LC_ALL="en_US.UTF-8"
#export EDITOR='vim'
#export PATH="/anaconda3/bin:$PATH"
#export LESS=-FXJAIMqj.5

# Path to your oh-my-zsh installation
# USERID=`whoami`
# MY_HOME_DIR=`finger $USERID |awk -F: '{print $2}' |awk '{print $1}' |head -2 |tail -1`
# OH_MY_ZSH_SUFFIX="/.dotfiles/oh-my-zsh"
# #export ZSH=$HOME$OH_MY_ZSH_SUFFIX
# #export ZSH=${HOME}/.zgen/robbyrussell/oh-my-zsh-master
#export OMZSHDIR=${DOTFILES}/plugins/from_omzsh
#export OMZSHCUSTOM=${DOTFILES}/custom

#export TERM=screen-256color
#export TERM=xterm-256color

# load powerlevel9k theme
source ${DOTFILES}/themes/powerlevel9k-master/powerlevel9k.zsh-theme
POWERLEVEL9K_MODE='awsome-patched'
ZSH_THEME="powerlevel9k/powerlevel9k"


# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# User configuration

# You may need to manually set your language environment
#export LANG=en_US.UTF-8
#export LC_ALL="en_US.UTF-8"

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   #export EDITOR='vim'
# else
#   #export EDITOR='mvim'
# fi
#export EDITOR='vim'

# ssh
# #export SSH_KEY_PATH="~/.ssh/rsa_id"

# zsh tmux settings
# ZSH_TMUX_AUTOSTART='true'

## Powerlevel9k Settings
POWERLEVEL9K_HISTORY_BACKGROUND='green'

POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4

POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%F{red} \Uf1d0 %f %F{yellow}❯ "

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=false
POWERLEVEL9K_CONTEXT_ALWAYS_SHOW=true
POWERLEVEL9K_CONTEXT_ALWAYS_SHOW_USER=false

# Command prompt
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir_joined vcs custom_git_repo_name)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status anaconda root_indicator vi_mode date ssh)

# GitHub prompt
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=$'\uF113'


get_repo_name() {
    if [[ $(git rev-parse --is-inside-work-tree 2>/dev/null) ]]; then
        # local repo_url=$(git remote show origin |grep URL |grep Fetch)
        # local url_end=$(echo $repo_url |awk -F'/' '{print $NF}')
        local url_end=$(git remote show origin |grep URL |grep Fetch |awk -F'\' '{print $NF}' |awk '{print $3}' |awk -F'\/' '{print $NF}' |awk -F'.' '{print $1}')
        # if [[ $(echo $url_end |egrep -e 'git$') ]]; then
            # local repo_name=$(echo $url_end |awk -F'.' '{print $1}')
        # else
            # local repo_name=$url_end
        # fi
        local repo_name=$url_end
    else
        local repo_name=''
    fi
    echo -n $repo_name
}


POWERLEVEL9K_CUSTOM_GIT_REPO_NAME="get_repo_name"

# dir
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_first_and_last'

POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_STATUS_CROSS=true

# anaconda segment
POWERLEVEL9K_ANACONDA_LEFT_DELIMITER="\uE235 "
POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=""
POWERLEVEL9K_ANACONDA_BACKGROUND='cyan'
POWERLEVEL9K_ANACONDA_FOREGROUND='black'



# dumb terminal can be a vim dump terminal in that case don't try to load plugins
# this block of commands was relocated to ${DOTFILES}/config_masters/zgen which is
# linked to ${HOME}/.zgen.conf
if [ ! $TERM = dumb ]; then

    # load zgen
    ZGEN_DIR=${HOME}/.zgen
    source ${HOME}/.zgen.conf
    # source ${PLUGINS}/from_omzsh/autojump/autojump.plugin.zsh
    # source ${PLUGINS}/from_omzsh/debian/debian.plugin.zsh
    # source ${PLUGINS}/from_omzsh/systemd/systemd.plugin.zsh
    # source ${PLUGINS}/from_omzsh/sudo/sudo.plugin.zsh
    # source ${PLUGINS}/from_omzsh/taskwarrior/taskwarrior.plugin.zsh
    # source ${PLUGINS}/from_omzsh/tmuxinator/tmuxinator.plugin.zsh
    # source ${PLUGINS}/from_omzsh/vi-mode/vi-mode.plugin.zsh
    # source ${PLUGINS}/from_omzsh/vundle/vundle.plugin.zsh
    # source ${PLUGINS}/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
    # source ${PLUGINS}/aliases/aliases.plugin.zsh
    # source ${PLUGINS}/tpm/tpm.plugin.zsh
    # source ${PLUGINS}/my_tmux/my_tmux.plugin.zsh
fi


# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git)
plugins=(sudo git history taskwarrior tmux tmuxinator zsh-autosuggestions aliases tpm)
# source $ZSH/oh-my-zsh.sh


# specific for machine configuration, which I don't sync
if [ -f ~/.machinerc ]; then
    source ~/.machinerc
fi


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
# else
#    if [ -f "/anaconda3/etc/profile.d/conda.sh" ]; then
#        . "/anaconda3/etc/profile.d/conda.sh"
#    else
#        #export PATH="/anaconda3/bin:$PATH"
#    fi
# fi
# unset __conda_setup
# <<< conda initialize <<<

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# additional configuration for zsh
# Remove the history (fc -l) command from the history list when invoked.
setopt histnostore
# Remove superfluous blanks from each command line being added to the history list.
setopt histreduceblanks
# Do not exit on end-of-file. Require the use of exit or logout instead.
# setopt ignoreeof
# Print the exit value of programs with non-zero exit status.
setopt printexitvalue
# Do not share history
setopt no_share_history


# configuration for the less command
#export LESS=-FXJAIMqj.5

# load local tmux configurations
tmux source-file ~/.tmux-local.conf

# if profiling was on
if $PROFILING; then
    zprof
fi


# zsh-syntax-highlighting must be sourced as the last thing in this file
# zgen load zsh-users/zsh-syntax-highlighting
source ~/.dotfiles/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
